In [1]:
l=[1,2,3,45]
print(l)

[1, 2, 3, 45]


# Numpy

"Numerical Python" is a python library.....used for working with arrays.
Here arrays are stored in continuous places in the memory....(lists or tuples are not stored similarly)
Thus numpy arrays( called 'ndarrays') are faster in execution than lists and tuples.

Data Science: is a branch of computer science where we study how to store, use and analyze data for deriving information from it.

# Why is Numpy faster??
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

# Install numpy from the command prompt:

pip install numpy

In [1]:
import numpy as np #import numpy

In [3]:
a=np.array([1,2,34,5,567,4])
print(a)

[  1   2  34   5 567   4]


In [4]:
type(a)

numpy.ndarray

In [5]:
t=(1,2,3,5,6,785,34,23)
b=np.array(t)
print(b)

[  1   2   3   5   6 785  34  23]


In [6]:
print(np.__version__)

1.19.2


nested array: are arrays that have arrays as their elements

Dimension is the level of the nested array

In [7]:
a=np.array(10) # Dimension of array is zero
print(a)
print(a.ndim)

10
0


In [8]:
ar=np.array([[1,2,3],[4,5,6]]) #2D array.....matrix
print(ar)

[[1 2 3]
 [4 5 6]]


In [9]:
print(ar.ndim)

2


In [10]:
a = np.array(42) # 0 Dimensional
b = np.array([1, 2, 3, 4, 5]) # 1 Dimensional
c = np.array([[1, 2, 3], [4, 5, 6]]) # 2 Dimensional
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # 3 Dimensional

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [11]:
print(d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
a=np.array([1,2,3], ndmin=4) # create an ndarray with specified dimension
print(a)
print('dimension of a : '+ str(a.ndim))

[[[[1 2 3]]]]
dimension of a : 4


In [13]:
b = np.array([1, 2, 3, 4, 5])
for i in range(5):
    print('b['+str(i)+'] = '+str(b[i]))

b[0] = 1
b[1] = 2
b[2] = 3
b[3] = 4
b[4] = 5


In [2]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [3]:
c[1,1]

5

In [16]:
c[1,0] #array[row,column] ...both rows and columns start at zero

4

In [17]:
for i in range(2):
    print()
    for j in range(3):
        print(c[i,j], end='\t')


1	2	3	
4	5	6	

In [18]:
l=[[1, 2, 3], [4, 5, 6]]

In [19]:
print(l)
print()
print(c)

[[1, 2, 3], [4, 5, 6]]

[[1 2 3]
 [4 5 6]]


In [20]:
l[0][0]# print list of list

1

In [5]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [22]:
d[1,1,2]

60

In [6]:
# what is the index for 5?
d[0,1,1]

5

In [7]:
# what is the index for 20?
d[1,0,1]

20

In [8]:
#What is the index for 3?
d[0,0,2]

3

In [10]:
l=[1,2,3,4,5]
print(l[::-1])

[5, 4, 3, 2, 1]


In [26]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

print('Last element from 2nd dim: ', arr[1, -2]) #negative indexing

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim:  9


In [27]:
arr[-1,3]

9

In [28]:
a=np.array([1,2,3,4,5,5,6,7])
print(a)
l=[1,2,3,4,5,5,6,7]
print(l)

[1 2 3 4 5 5 6 7]
[1, 2, 3, 4, 5, 5, 6, 7]


In [29]:
print(2*a) #element wise multiplication
print()
print(2*l) # list is doubled

[ 2  4  6  8 10 10 12 14]

[1, 2, 3, 4, 5, 5, 6, 7, 1, 2, 3, 4, 5, 5, 6, 7]


In [30]:
b=np.array([10,20,30,40,50,55,60,70])
print(a)
print(b)
print(a+b) #element wise addition

[1 2 3 4 5 5 6 7]
[10 20 30 40 50 55 60 70]
[11 22 33 44 55 60 66 77]


In [31]:
# Slicing: array[start:end:step].....if start is not given it will be taken as 0, default value of step is one.
a[1:5] #array from index 1 upto 5

array([2, 3, 4, 5])

In [32]:
a[:7:2]

array([1, 3, 5, 6])

In [33]:
a[::-1] # REVERSE

array([7, 6, 5, 5, 4, 3, 2, 1])

In [34]:
a[-5:-2] # negative indexing

array([4, 5, 5])

In [35]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
arr[1,1:4]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([7, 8, 9])

In [36]:
print(arr)
arr[0:2,3]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([4, 9])

In [37]:
print(arr)
arr[0:2, 1:4]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[2, 3, 4],
       [7, 8, 9]])